level_0 = {
		'terrain': 'levels/0/0_level_tiles.csv',
		'terrain_folder': 'graphics/tirrein',
		'coins': 'levels/0/0_level_coins.csv',
		'player': 'levels/0/0_level_game.csv',
        'decorations': 'levels/0/0_level_decorates.csv',
		'obstacles': 'levels/0/0_level_obstacles.csv',
		'obstacles_folder': 'graphics/obstacles/cutting_disc',
		'limitations_enemy': 'levels/0/0_level_limitations_monsters.csv',
		'enemies': 'levels/0/0_level_monsters.csv',
	    'background': 'graphics/background/level_0_Mars.png',
		'color_text_scale': (100, 100, 80),
		'damage player':  5,
		'gravity_player': 0.6,
		'asteroid_generation_coefficient': 0,
		'PATH_ASTEROID': 'graphics/animate_asteroid/',
		'PATH_EXR_ASTEROID': 'graphics/explosions/2',
		'damage_asteroid': 100,
		'tile size': 128
}

level_1 = {'terrain': 'levels/1/1_level_tiles.csv',
		'terrain_folder': 'graphics/tirrein1',
		'coins': 'levels/1/1_level_coins.csv',
		'player': 'levels/1/1_level_game.csv',
		'decorations': 'levels/empty folder.csv',
		'obstacles': 'levels/1/1_level_lava.csv',
		'obstacles_folder': 'graphics/obstacles/lava_draw',
		'limitations_enemy': 'levels/1/1_level_limitations_monsters.csv',
		'enemies': 'levels/1/1_level_monsters.csv',
		'background': 'graphics/background/level_1_fare_planet.png ',
		'color_text_scale': (255, 200, 80),
		'damage player': 5,
		'gravity_player': 0.8,
		'asteroid_generation_coefficient': 12,
		'PATH_ASTEROID': 'graphics/animate_asteroid/',
		'PATH_EXR_ASTEROID': 'graphics/explosions/2',
		'damage_asteroid': 100,
		'tile size': 64,
		}

level_2 = {
		'terrain': 'levels/2/2_level_tiles.csv',
		'terrain_folder': 'graphics/tirrein2',
		'coins': 'levels/2/2_level_coins.csv',
		'player': 'levels/2/2_level_game.csv',
        'decorations': 'levels/empty folder.csv',
		'obstacles': 'levels/2/2_level_obstacles.csv',
		'obstacles_folder': 'graphics/obstacles/cutting_disc',
		'limitations_enemy': 'levels/2/2_level_limitations_monsters.csv',
		'enemies': 'levels/2/2_level_monsters.csv',
	    'background': 'graphics/background/level_2_frozen_planet.png',
		'color_text_scale': (100, 80, 180),
		'damage player':  5,
		'gravity_player': 0.85,
		'asteroid_generation_coefficient': 100,
		'PATH_ASTEROID': 'graphics/snowball/',
		'PATH_EXR_ASTEROID': 'graphics/explosions/3',
		'damage_asteroid': 20,
		'tile size': 64
}

level_3 = {
		'terrain': 'levels/3/3_level_tiles.csv',
		'terrain_folder': 'graphics/tirrein3',
		'coins': 'levels/3/3_level_coins.csv',
		'player': 'levels/3/3_level_game.csv',
        'decorations': 'levels/empty folder.csv',
		'obstacles': 'levels/3/3_level_obstacles.csv',
		'obstacles_folder': 'graphics/obstacles/thorns',
		'limitations_enemy': 'levels/3/3_level_limitations_monsters.csv',
		'enemies': 'levels/3/3_level_monsters.csv',
	    'background': 'graphics/background/level_3_swamp_planet.png',
		'color_text_scale': (250, 255, 250),
		'damage player':  5,
		'gravity_player': 0.92,
		'asteroid_generation_coefficient': 0,
		'PATH_ASTEROID': 'graphics/animate_asteroid/',
		'PATH_EXR_ASTEROID': 'graphics/explosions/2',
		'damage_asteroid': 100,
		'tile size': 64,
		'color_rising_substance': (105, 131, 57)
}

level_4 = {
		'terrain': 'levels/4/4_level_tiles.csv',
		'terrain_folder': 'graphics/tirrein4',
		'coins': 'levels/4/4_level_coins.csv',
		'player': 'levels/4/4_level_game.csv',
        'decorations': 'levels/empty folder.csv',
		'obstacles': 'levels/4/4_level_obstacles.csv',
		'obstacles_folder': 'graphics/obstacles/cutting_disc',
		'limitations_enemy': 'levels/empty folder.csv',
		'enemies': 'levels/empty folder.csv',
	    'background': 'graphics/background/level_4_city_planet.png',
		'color_text_scale': (150, 200, 200),
		'damage player':  5,
		'gravity_player': 0.8,
		'asteroid_generation_coefficient': 0,
		'PATH_ASTEROID': 'graphics/animate_asteroid/',
		'PATH_EXR_ASTEROID': 'graphics/explosions/2',
		'damage_asteroid': 100,
		'tile size': 128
}
