level_0 = {
		'terrain': 'levels/0/0_level_tiles.csv',
		'terrain_folder': 'graphics/tirrein',
		'coins': 'levels/0/0_level_coins.csv',
		'player': 'levels/0/0_level_game.csv',
        'decorations': 'levels/0/0_level_decorates.csv',
		'obstacles': 'levels/0/0_level_obstacles.csv',
		'obstacles_folder': 'graphics/obstacles/cutting_disc',
		'limitations_enemy': 'levels/0/0_level_limitations_monsters.csv',
		'enemies': 'levels/0/0_level_monsters.csv',
	    'background': 'graphics/background/level_0_Mars.png',
		'color_text_scale': (100, 100, 80),
		'damage player':  5,
		'gravity_player': 0.6,
		'asteroid_generation_coefficient': 0,
		'tile size': 128
}

level_1 = {'terrain': 'levels/1/1_level_tiles.csv',
		'terrain_folder': 'graphics/tirrein1',
		'coins': 'levels/1/1_level_coins.csv',
		'player': 'levels/1/1_level_game.csv',
		'decorations': 'levels/empty folder.csv',
		'obstacles': 'levels/1/1_level_lava.csv',
		'obstacles_folder': 'graphics/obstacles/lava',
		'limitations_enemy': 'levels/1/1_level_limitations_monsters.csv',
		'enemies': 'levels/1/1_level_monsters.csv',
		'background': 'graphics/background/level_1_fare_planet.png ',
		'color_text_scale': (255, 200, 80),
		'damage player': 5,
		'gravity_player': 0.8,
		'asteroid_generation_coefficient': 12,
		'tile size': 64,
		}
